# BGP - Variables globales + interconnects (generes automatiquement)

bgp_max_paths: 4
bgp_max_routes: 12000
bgp_asn_spines: 66000
leafs_asn:
  1: 66001
  2: 66001
  3: 66002
  4: 66002
interconnects:
- spine: 1
  leaf: 1
  spine_name: dc2-spine-1
  leaf_name: dc2-leaf-1
  network: 172.16.100.0/31
  spine_ip: 172.16.100.0
  leaf_ip: 172.16.100.1
  spine_eth: 6
  leaf_eth: 1
- spine: 1
  leaf: 2
  spine_name: dc2-spine-1
  leaf_name: dc2-leaf-2
  network: 172.16.100.2/31
  spine_ip: 172.16.100.2
  leaf_ip: 172.16.100.3
  spine_eth: 5
  leaf_eth: 1
- spine: 1
  leaf: 3
  spine_name: dc2-spine-1
  leaf_name: dc2-leaf-3
  network: 172.16.100.4/31
  spine_ip: 172.16.100.4
  leaf_ip: 172.16.100.5
  spine_eth: 1
  leaf_eth: 1
- spine: 1
  leaf: 4
  spine_name: dc2-spine-1
  leaf_name: dc2-leaf-4
  network: 172.16.100.6/31
  spine_ip: 172.16.100.6
  leaf_ip: 172.16.100.7
  spine_eth: 2
  leaf_eth: 1
- spine: 2
  leaf: 1
  spine_name: dc2-spine-2
  leaf_name: dc2-leaf-1
  network: 172.16.100.8/31
  spine_ip: 172.16.100.8
  leaf_ip: 172.16.100.9
  spine_eth: 6
  leaf_eth: 2
- spine: 2
  leaf: 2
  spine_name: dc2-spine-2
  leaf_name: dc2-leaf-2
  network: 172.16.100.10/31
  spine_ip: 172.16.100.10
  leaf_ip: 172.16.100.11
  spine_eth: 5
  leaf_eth: 2
- spine: 2
  leaf: 3
  spine_name: dc2-spine-2
  leaf_name: dc2-leaf-3
  network: 172.16.100.12/31
  spine_ip: 172.16.100.12
  leaf_ip: 172.16.100.13
  spine_eth: 1
  leaf_eth: 2
- spine: 2
  leaf: 4
  spine_name: dc2-spine-2
  leaf_name: dc2-leaf-4
  network: 172.16.100.14/31
  spine_ip: 172.16.100.14
  leaf_ip: 172.16.100.15
  spine_eth: 2
  leaf_eth: 2
