# BGP - Variables globales + interconnects (generes automatiquement)

bgp_max_paths: 4
bgp_max_routes: 12000
bgp_asn_spines: 64000
leafs_asn:
  1: 64001
  2: 64001
  3: 64002
  4: 64002
  5: 64003
  6: 64003
interconnects:
- spine: 1
  leaf: 1
  spine_name: dc1-spine-1
  leaf_name: dc1-leaf-1
  network: 10.0.0.0/31
  spine_ip: 10.0.0.0
  leaf_ip: 10.0.0.1
  spine_eth: 1
  leaf_eth: 1
- spine: 1
  leaf: 2
  spine_name: dc1-spine-1
  leaf_name: dc1-leaf-2
  network: 10.0.0.2/31
  spine_ip: 10.0.0.2
  leaf_ip: 10.0.0.3
  spine_eth: 3
  leaf_eth: 1
- spine: 1
  leaf: 3
  spine_name: dc1-spine-1
  leaf_name: dc1-leaf-3
  network: 10.0.0.4/31
  spine_ip: 10.0.0.4
  leaf_ip: 10.0.0.5
  spine_eth: 4
  leaf_eth: 1
- spine: 1
  leaf: 4
  spine_name: dc1-spine-1
  leaf_name: dc1-leaf-4
  network: 10.0.0.6/31
  spine_ip: 10.0.0.6
  leaf_ip: 10.0.0.7
  spine_eth: 2
  leaf_eth: 2
- spine: 1
  leaf: 5
  spine_name: dc1-spine-1
  leaf_name: dc1-leaf-5
  network: 10.0.0.8/31
  spine_ip: 10.0.0.8
  leaf_ip: 10.0.0.9
  spine_eth: 5
  leaf_eth: 1
- spine: 1
  leaf: 6
  spine_name: dc1-spine-1
  leaf_name: dc1-leaf-6
  network: 10.0.0.10/31
  spine_ip: 10.0.0.10
  leaf_ip: 10.0.0.11
  spine_eth: 6
  leaf_eth: 1
- spine: 2
  leaf: 1
  spine_name: dc1-spine-2
  leaf_name: dc1-leaf-1
  network: 10.0.0.12/31
  spine_ip: 10.0.0.12
  leaf_ip: 10.0.0.13
  spine_eth: 2
  leaf_eth: 2
- spine: 2
  leaf: 2
  spine_name: dc1-spine-2
  leaf_name: dc1-leaf-2
  network: 10.0.0.14/31
  spine_ip: 10.0.0.14
  leaf_ip: 10.0.0.15
  spine_eth: 3
  leaf_eth: 2
- spine: 2
  leaf: 3
  spine_name: dc1-spine-2
  leaf_name: dc1-leaf-3
  network: 10.0.0.16/31
  spine_ip: 10.0.0.16
  leaf_ip: 10.0.0.17
  spine_eth: 4
  leaf_eth: 2
- spine: 2
  leaf: 4
  spine_name: dc1-spine-2
  leaf_name: dc1-leaf-4
  network: 10.0.0.18/31
  spine_ip: 10.0.0.18
  leaf_ip: 10.0.0.19
  spine_eth: 1
  leaf_eth: 1
- spine: 2
  leaf: 5
  spine_name: dc1-spine-2
  leaf_name: dc1-leaf-5
  network: 10.0.0.20/31
  spine_ip: 10.0.0.20
  leaf_ip: 10.0.0.21
  spine_eth: 5
  leaf_eth: 2
- spine: 2
  leaf: 6
  spine_name: dc1-spine-2
  leaf_name: dc1-leaf-6
  network: 10.0.0.22/31
  spine_ip: 10.0.0.22
  leaf_ip: 10.0.0.23
  spine_eth: 6
  leaf_eth: 2
