# Variables specifiques a dc2-leaf-3 (generees automatiquement)

loopback0_ip: 172.24.0.13
bgp_asn: 64002
mlag_ip: 200.0.0.2
mlag_peer_ip: 200.0.0.3
virtual_router_mac: 00:1c:73:00:00:18
loopback1_ip: 2.2.1.2
loopback_test_id: 100
loopback_test_ip: 20.20.20.30
route_distinguisher: 3000
bgp_networks:
- 172.24.0.13/32
svis: []
is_border_leaf: true
dci_links:
- eth: 5
  neighbor: dc2-isn-2
  local_ip: 20.0.0.20
  remote_ip: 20.0.0.21
  prefix: 31
  remote_asn: 65100
  rt_import: 1:9999
  rt_export: 1:9999
  vni_l3: 5001
  isn_loopback0: 172.16.100.2
