# Variables specifiques a dc1-leaf-2 (generees automatiquement)

loopback0_ip: 172.16.0.12
bgp_asn: 65001
mlag_ip: 100.0.0.1
mlag_peer_ip: 100.0.0.0
virtual_router_mac: 00:1c:73:00:00:0c
loopback1_ip: 1.1.2.1
loopback_test_id: 100
loopback_test_ip: 10.10.10.20
route_distinguisher: 1000
bgp_networks:
- 172.16.115.0/24
- 172.16.116.0/24
- 172.16.0.12/32
svis:
- vlan_id: 115
  ip: 172.16.115.3
  prefix: 24
  virtual_ip: 172.16.115.1
  eth_int_host: 6
  vni: 10115
- vlan_id: 116
  ip: 172.16.116.3
  prefix: 24
  virtual_ip: 172.16.116.1
  eth_int_host: 7
  vni: 10116
is_border_leaf: false
dci_links: []
