# MLAG - Variables globales

mgmt_gateway: 192.168.28.254
mlag_vlan: 4094
mlag_peer_name: lag
mlag_netmask: 31
mlag_channel_group: 4094
trunk_group_name: mlag-peer
mlag_peer_first_eth_int: 3
mlag_peer_second_eth_int: 4
